package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AULIA NUR RACHMATIKA
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksii;
import objek.pribadi;

public class alat_prib extends javax.swing.JFrame {
    pribadi pb = new pribadi();

    int jumlah, harga, totalbayar;
    String NamaBarang;

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("NAMA ALAT");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
          tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

    }

    private void clear() {

        cb_pilih.setSelectedItem(null);
        txt_harga.setText(null);
        txt_jumlah.setText(null);
        txt_total.setText(null);

    }

    /**
     * Creates new form alat_prib
     */
    public alat_prib() {
        initComponents();
       
       tampilData();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_pilih = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_cekout = new javax.swing.JButton();
        btn_savee = new javax.swing.JButton();
        btnhps = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txt = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALAT PRIBADI YANG TERSEDIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 176, 26));

        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 55, -1, -1));

        jLabel3.setText("HARGA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 80, -1, -1));

        jLabel4.setText("JUMLAH");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 112, -1, -1));

        jLabel5.setText("TOTAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 147, -1, -1));

        cb_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "JAKET DOUBLE POLAR", "SEPATU TRACKING", "MATRAS", "FLYSHEET 3X3 M", "SLEEPING BAG", "SARUNG TANGAN POLAR", "RAIN COAT", "TRACKING POLE", "WEBBING", " " }));
        cb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihActionPerformed(evt);
            }
        });
        getContentPane().add(cb_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, -1));
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 86, 84, -1));

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 84, -1));

        btn_tambah.setText("TAMBAH ALAT");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        btn_cekout.setText("CHECKOUT");
        btn_cekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        btn_savee.setText("SAVE");
        btn_savee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_savee, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 291, -1, -1));

        btnhps.setText("HAPUS");
        btnhps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhpsActionPerformed(evt);
            }
        });
        getContentPane().add(btnhps, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 291, -1, -1));

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalKeyReleased(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 84, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 560, 200));

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 90, 20));

        jTextField1.setText("TOTAL BAYAR");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 260, 90, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bg2.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed
public void sum(){
        int total=0;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            int amount=Integer.parseInt((String)tbl.getValueAt(i, 4));
            total+=amount;
            
        }
         txt.setText(""+total);
        
    }
    private void cb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihActionPerformed
        // TODO add your handling code here:
        NamaBarang = (String) cb_pilih.getSelectedItem();
        if (NamaBarang == null) {
        } else {
            switch (NamaBarang) {
                case "JAKET DOUBLE POLAR":
                    harga = 25000;
                    break;
                case "SEPATU TRACKING":
                    harga = 20000;
                    break;
                case "SLEEPING BAG":
                    harga = 15000;
                    break;
                case "RAIN COAT":
                    harga = 8000;
                    break;
                case "TRACKING POLE":
                    harga = 8000;
                    break;
                case "FLYSHEET 3X3 M":
                    harga = 9000;
                    break;
                case "MATRAS":
                    harga = 3000;
                    break;
                case "SARUNG TANGAN POLAR":
                    harga = 3000;
                    break;
                default:
                    break;
            }
        }
        txt_harga.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_pilihActionPerformed

    private void txt_totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyReleased

    }//GEN-LAST:event_txt_totalKeyReleased

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(txt_harga.getText());
        b = Integer.valueOf(txt_jumlah.getText());
        c = a * b;
        txt_total.setText(String.valueOf(c));
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void btn_saveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("NAMA ALAT");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

        try {
            String sql = "INSERT INTO barang VALUES('" + cb_pilih.getSelectedItem() + "','" + txt_harga.getText() + "','" + txt_jumlah.getText() + "','" + txt_total.getText() + "')";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Simpan data sukses");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
       tampilData();
 
        clear();
        sum();


    }//GEN-LAST:event_btn_saveeActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int baris = tbl.rowAtPoint(evt.getPoint());
        String nama = tbl.getValueAt(baris, 1).toString();
        cb_pilih.setSelectedItem(nama);
        String harga = tbl.getValueAt(baris, 2).toString();
        txt_harga.setText(harga);
        String jumlah = tbl.getValueAt(baris, 3).toString();
        txt_jumlah.setText(jumlah);
        String total = tbl.getValueAt(baris, 4).toString();
        txt_total.setText(total);
    }//GEN-LAST:event_tblMouseClicked

    private void btnhpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhpsActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM barang WHERE NAMA_ALAT='" + cb_pilih.getSelectedItem() + "'";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Hapus data sukses");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
      tampilData();
    
        clear();

    }//GEN-LAST:event_btnhpsActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        AlatRental ar = new AlatRental();
        ar.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_cekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekoutActionPerformed
        // TODO add your handling code here:
        Input sw = new Input();
        sw.setVisible(true);
    }//GEN-LAST:event_btn_cekoutActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alat_prib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alat_prib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alat_prib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alat_prib.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alat_prib().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cekout;
    private javax.swing.JButton btn_savee;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btnhps;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
