/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksii;

/**
 *
 * @author AULIA NUR RACHMATIKA
 */
public class finish extends javax.swing.JFrame {

    public finish() {
        initComponents();
        tampilData();
    }
 public void sum() {
        int total = 0;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tbl.getValueAt(i, 4));
            double hari= Double.parseDouble ((String) this.hari.getText());
            total += amount*hari;

        }
        bayarr.setText("" + total);

    }
    public void setNama(JTextField data1, JTextField data2, JTextField data3, JTextField data4) {
        txt.setText("Nama  : " + data1.getText()+"\n"
                + "Email : " + data2.getText()+"\n"
                + "Alamat :  " + data3.getText()+"\n"
                + "No Telp : " + data4.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btn_finish = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        bayar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bayarr = new javax.swing.JTextField();
        btn_finish1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hari1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bayarr1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_finish2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 500, 150));

        btn_finish.setText("BAYAR");
        btn_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finishActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane2.setViewportView(txt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 291, 78));
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1691, 1058, 132, -1));

        jLabel1.setText("TOTAL BAYAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 104, 30));

        jLabel2.setText("HARGA SEWA DIHITUNG PER HARI ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 254, 16));

        jLabel4.setText("LAMA PINJAM (HARI)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        getContentPane().add(hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 3, 14)); // NOI18N
        jLabel5.setText("NB:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 58, -1));

        jLabel6.setText("BERIKAN KARTU IDENTITAS SEBAGAI JAMINAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        jLabel7.setText("BAWA NOTA INI JIKA INGIN MENGEMBALIKAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1519, 1154, 245, -1));

        jLabel8.setText("TELAT PER HARI+DENDA PER ITEM");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel9.setText("APABILA ADA KERUSAKAN/KEHILANGAN ADALAH TANGGUNG JAWAB PENYEWA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        bayarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarrActionPerformed(evt);
            }
        });
        getContentPane().add(bayarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 188, -1));

        btn_finish1.setText("BAYAR");
        btn_finish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finish1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finish1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 1058, -1, -1));

        jLabel11.setText("TOTAL BAYAR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 790, 104, 30));

        jLabel12.setText("HARGA SEWA DIHITUNG PER 2 HARI ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1221, 254, 16));

        jLabel13.setText("HARGA BERLAKU SESUAI HARI, JIKA HANYA 1 ATAU +1  HARI DIHITUNG SETENGAH");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1243, -1, -1));

        hari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hari1ActionPerformed(evt);
            }
        });
        getContentPane().add(hari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 910, 190, -1));

        jLabel14.setText("NB:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1201, 58, -1));

        jLabel15.setText("BERIKAN KARTU IDENTITAS SEBAGAI JAMINAN");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1303, -1, -1));

        jLabel16.setText("TELAT PER HARI+DENDA PER ITEM");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1263, -1, -1));

        jLabel17.setText("APABILA ADA KERUSAKAN/KEHILANGAN ADALAH TANGGUNG JAWAB PENYEWA");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1283, -1, -1));

        bayarr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarr1ActionPerformed(evt);
            }
        });
        getContentPane().add(bayarr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 870, 188, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jLabel19.setText("BAWA NOTA INI JIKA SAAT MENGEMBALIKAN ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, 30));

        jButton1.setText("CETAK");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        btn_finish2.setText("BAYAR");
        btn_finish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finish2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_finish2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        jButton2.setText("INPUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        jLabel3.setText("TANGGAL PINJAM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 190, -1));

        jLabel10.setText("TANGGAL KEMBALI");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 190, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cihuy.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("Nama Alat");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total Bayar");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

    }
    private void btn_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finishActionPerformed
        // TODO add your handling code here:
        tampilData();
        Input ip = new Input();
        ip.txt_nama.getText();
        sum();

    }//GEN-LAST:event_btn_finishActionPerformed

    private void btn_finish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finish1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_finish1ActionPerformed

    private void bayarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarrActionPerformed

    private void hari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hari1ActionPerformed

    private void bayarr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarr1ActionPerformed

    private void btn_finish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finish2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_finish2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        penyewa ip = new penyewa();
        ip.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bayar;
    private javax.swing.JTextField bayarr;
    private javax.swing.JTextField bayarr1;
    private javax.swing.JButton btn_finish;
    private javax.swing.JButton btn_finish1;
    private javax.swing.JButton btn_finish2;
    private javax.swing.JTextField hari;
    private javax.swing.JTextField hari1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbl;
    public javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
