/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksii;
import objek.Alatnavigasi;

/**
 *
 * @author AULIA NUR RACHMATIKA
 */
public class navigasi extends javax.swing.JFrame {
    
    Alatnavigasi an = new Alatnavigasi();
    


    int jumlah, harga, totalbayar;
    String NamaBarang;



    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("Nama Alat");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total Bayar");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

    }

    private void clear() {

        cb_barang.setSelectedItem(null);
        txt_harga.setText(null);
        txt_jumlah.setText(null);
        txt_yotal.setText(null);

    }

    /**
     * Creates new form navigasi
     */
    public navigasi() {
        initComponents();
       
        tampilData();
        clear();
        sum();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        cb_barang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_yotal = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btn_cekout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        har = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alat Navigasi yang tersedia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 159, 47));

        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 249, -1, -1));

        cb_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "KOMPAS", "PELUIT" }));
        cb_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_barangActionPerformed(evt);
            }
        });
        getContentPane().add(cb_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 70, 140, -1));

        jLabel2.setText("NAMA BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 76, 116, 9));

        jLabel3.setText("HARGA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 119, 116, -1));

        jLabel4.setText("JUMLAH");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 154, 116, -1));

        txt_total.setText("TOTAL BAYAR");
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 192, 116, -1));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 116, 66, -1));

        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 154, 66, -1));

        txt_yotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yotalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_yotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 192, 66, -1));

        btn_tambah.setText("TAMBAH ALAT");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 249, -1, -1));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, -1, 680));

        btn_cekout.setText("CHECKOUT");
        btn_cekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 290, -1, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 60, 510, 104));

        save.setText("SIMPAN");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 290, -1, -1));

        delete.setText("HAPUS");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 249, -1, -1));
        getContentPane().add(har, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 192, -1, -1));

        jTextField1.setText("TOTAL BAYAR");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 105, -1));
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 96, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\AULIA NUR RACHMATIKA\\Desktop\\java\\bg2.jpeg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        AlatRental ar = new AlatRental();
        ar.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btn_backActionPerformed
    int a, b, c;

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void cb_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_barangActionPerformed
        // TODO add your handling code here:
        NamaBarang = (String) cb_barang.getSelectedItem();

        if (NamaBarang == "KOMPAS") {
            harga = 15000;

        } else if (NamaBarang == "PELUIT") {
            harga = 15000;
        }

        txt_harga.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_barangActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        int a, b, c;
        a = Integer.valueOf(txt_harga.getText());
        b = Integer.valueOf(txt_jumlah.getText());
        c = a * b;
        txt_yotal.setText(String.valueOf(c));
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        AlatRental ar = new AlatRental();
        
        ar.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_cekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekoutActionPerformed
        // TODO add your handling code here:
        Input sw = new Input();
        sw.setVisible(true);

    }//GEN-LAST:event_btn_cekoutActionPerformed
     public void sum() {
        int total = 0;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tbl.getValueAt(i, 4));
            total += amount;

        }
     bayar.setText("" + total);

    }
    private void txt_yotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yotalActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("NAMA ALAT");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

        try {
            String sql = "INSERT INTO barang VALUES('" + cb_barang.getSelectedItem() + "','" + txt_harga.getText() + "','" + txt_jumlah.getText() + "','" + txt_yotal.getText() + "')";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Simpan data sukses");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        tampilData();
        clear();
        sum();


    }//GEN-LAST:event_saveActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int baris = tbl.rowAtPoint(evt.getPoint());
        String nama = tbl.getValueAt(baris, 1).toString();
        cb_barang.setSelectedItem(nama);

        String harga = tbl.getValueAt(baris, 2).toString();
        txt_harga.setText(harga);

        String jumlah = tbl.getValueAt(baris, 3).toString();
        txt_jumlah.setText(jumlah);

        String total = tbl.getValueAt(baris, 4).toString();
        txt_yotal.setText(total);

    }//GEN-LAST:event_tblMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM barang WHERE NAMA_ALAT='" + cb_barang.getSelectedItem() + "'";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Hapus data sukses");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        tampilData();
        clear();
        sum();

    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(navigasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(navigasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(navigasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(navigasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new navigasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cekout;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_barang;
    private javax.swing.JButton delete;
    private javax.swing.JLabel har;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton save;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JLabel txt_total;
    public javax.swing.JTextField txt_yotal;
    // End of variables declaration//GEN-END:variables
}
