package GUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.koneksii;
import javax.swing.table.DefaultTableModel;
import objek.Penyewa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AULIA NUR RACHMATIKA
 */
public class penyewa extends javax.swing.JFrame {
    
private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("Kode Penyewa");
        model.addColumn("Email");
        model.addColumn("Alamat");
        model.addColumn("NO.TELP");

        try {
            int no = 1;
            String sql = "SELECT *FROM sewa";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
                btn_tabel.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

    }
    private void clearfrom() {

        btn_kode.setText(null);
        btn_email.setText(null);
        btn_alamat.setText(null);
        btn_tlp.setText(null);

    }

 
//            btn_tabel.setModel(model);

    public penyewa() {
        initComponents();
        clearfrom();
      tampilData();
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kode = new javax.swing.JTextField();
        btn_email = new javax.swing.JTextField();
        btn_alamat = new javax.swing.JTextField();
        btn_tlp = new javax.swing.JTextField();
        btn_data = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btn_tabel = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_delet = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Penyewa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 166, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kode penyewa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btn_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kodeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 166, -1));

        btn_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emailActionPerformed(evt);
            }
        });
        getContentPane().add(btn_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 166, -1));

        btn_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 166, -1));

        btn_tlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tlpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 166, -1));

        btn_data.setText("ADD DATA");
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 60, -1));

        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel2.setText("NO.TELP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 54, 20));

        btn_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        btn_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(btn_tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 640, 190));

        jLabel6.setText("DAFTAR PENYEWA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 210, 40));

        btn_delet.setText("DELETE");
        btn_delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cihuy.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_emailActionPerformed

    private void btn_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_alamatActionPerformed

    private void btn_tlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tlpActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        HOME hm = new HOME();
        hm.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        clearfrom();

    }//GEN-LAST:event_btn_dataActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       
        
       Penyewa pw = new Penyewa();
     
       pw.setKodePenyewa(btn_kode.getText());
       pw.setEmail(btn_email.getText());
       pw.setAlamat(btn_alamat.getText());
       pw.setNoTelp(btn_tlp.getText());
       pw.getAlamat();
       pw.getEmail();
       pw.getKodePenyewa();
       pw.getNoTelp();
       pw.sewa();
       tampilData();
       
       
       
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tabelMouseClicked
        int baris = btn_tabel.rowAtPoint(evt.getPoint());
        String kode = btn_tabel.getValueAt(baris, 1).toString();
        btn_kode.setText(kode);

        String email = btn_tabel.getValueAt(baris, 2).toString();
        btn_email.setText(email);

        String alamat = btn_tabel.getValueAt(baris, 3).toString();
        btn_alamat.setText(alamat);

        String telp = btn_tabel.getValueAt(baris, 4).toString();
        btn_tlp.setText(telp);


    }//GEN-LAST:event_btn_tabelMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE sewa SET Kode_Penyewa='" + btn_kode.getText() + "',Email='" + btn_email.getText() + "',Alamat='" + btn_alamat.getText() + "',NO_TELP='" + btn_tlp.getText() + "' WHERE KODE_PENYEWA='"+btn_kode.getText()+"'";
            java.sql.Connection cn =(Connection)koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Edit data berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
            tampilData();
            clearfrom();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kodeActionPerformed

    private void btn_deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletActionPerformed
        // TODO add your handling code here:
                try{
            String sql="DELETE FROM sewa  WHERE KODE_PENYEWA='"+btn_kode.getText()+"'";
            java.sql.Connection cn =(Connection)koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Hapus data berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
            tampilData();
            clearfrom();
    }//GEN-LAST:event_btn_deletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btn_alamat;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_data;
    private javax.swing.JButton btn_delet;
    private javax.swing.JButton btn_edit;
    private javax.swing.JTextField btn_email;
    private javax.swing.JTextField btn_kode;
    private javax.swing.JButton btn_save;
    private javax.swing.JTable btn_tabel;
    private javax.swing.JTextField btn_tlp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
