/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksii;
import objek.tas;

/**
 *
 * @author AULIA NUR RACHMATIKA
 */
public class Tascariel extends javax.swing.JFrame {
    tas ts = new tas ();
    

    int jumlah, harga, totalbayar;
    String NamaBarang;
    
    
    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("NAMA ALAT");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
        
    }

    private void clear() {
       
        cb_pilih.setSelectedItem(null);
        txt_harga.setText(null);
        txt_jumlah.setText(null);
        txt_total.setText(null);

    }

    /**
     * Creates new form Tascariel
     */
    public Tascariel() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        cb_pilih = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        CHECKOUT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("TOTAL");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 221, -1, -1));

        cb_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "CARRIER JACK WOLFSKIN DENALI 60 L", "CARRIER EIGER RHINOS 60 L", "CARRIER EIGER RHINOS 45 L", "CARRIER AVTECH STORM 70 L", "CARRIER DEUTER FOX 40 L" }));
        cb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihActionPerformed(evt);
            }
        });
        jDesktopPane1.add(cb_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 96, -1, -1));
        jDesktopPane1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 136, 107, -1));

        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        jDesktopPane1.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 176, 107, -1));
        jDesktopPane1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 218, 107, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 138));

        jLabel5.setText("CARIEL");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 23, 163, 25));

        jLabel1.setText("NAMA ALAT");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 99, 73, -1));

        jLabel2.setText("HARGA");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 139, 62, -1));

        jLabel3.setText("JUMLAH");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 179, -1, -1));

        btn_hapus.setText("DELETE");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 289, -1, -1));

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 289, -1, -1));

        CHECKOUT.setText("CHECKOUT");
        CHECKOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKOUTActionPerformed(evt);
            }
        });
        jDesktopPane1.add(CHECKOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 341, -1, -1));

        jButton4.setText("jButton1");
        jDesktopPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1177, -1, -1));

        btn_tambah.setText("TAMBAH ALAT");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 341, -1, -1));

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        jDesktopPane1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 99, -1));

        jTextField1.setText("TOTAL BAYAR");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 91, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bg2.jpeg"))); // NOI18N
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, -1, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(670, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihActionPerformed
        // TODO add your handling code here:
        NamaBarang = (String) cb_pilih.getSelectedItem();
        if (NamaBarang == "CARRIER JACK WOLFSKIN DENALI 60 L") {
            harga = 24000;
        } else if (NamaBarang == "CARRIER EIGER RHINOS 60 L") {
            harga = 24000;
        } else if (NamaBarang == "CARRIER EIGER RHINOS 45 L") {
            harga = 23000;
        } else if (NamaBarang == "CARRIER AVTECH STORM 70 L") {
            harga = 25000;

        } else if (NamaBarang == "CARRIER DEUTER FOX 40 L") {
            harga = 23000;
        }
        txt_harga.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_pilihActionPerformed

    private void CHECKOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKOUTActionPerformed
        // TODO add your handling code here:
        Input sw = new Input();
        sw.setVisible(true);
    }//GEN-LAST:event_CHECKOUTActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(txt_harga.getText());
        b = Integer.valueOf(txt_jumlah.getText());
        c = a * b;
        txt_total.setText(String.valueOf(c));
    }//GEN-LAST:event_txt_jumlahKeyReleased
    public void sum() {
        int total = 0;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tbl.getValueAt(i, 4));
            total += amount;

        }
        txt.setText("" + total);

    }
    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM barang WHERE Nama_Alat='" + cb_pilih.getSelectedItem() + "'";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Hapus data sukses");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampilData();
        clear();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("NAMA ALAT");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

        try {
            String sql = "INSERT INTO barang VALUES('" + cb_pilih.getSelectedItem() + "','" + txt_harga.getText() + "','" + txt_jumlah.getText() + "','" + txt_total.getText() + "')";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Simpan data sukses");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
       
       

        tampilData();
        clear();
        sum();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int baris = tbl.rowAtPoint(evt.getPoint());
        String nama = tbl.getValueAt(baris, 1).toString();
        cb_pilih.setSelectedItem(nama);

        String harga = tbl.getValueAt(baris, 2).toString();
        txt_harga.setText(harga);

        String jumlah = tbl.getValueAt(baris, 3).toString();
        txt_jumlah.setText(jumlah);

        String total = tbl.getValueAt(baris, 4).toString();
        txt_total.setText(total);

    }//GEN-LAST:event_tblMouseClicked

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        AlatRental ar = new AlatRental();
        ar.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tascariel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tascariel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tascariel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tascariel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tascariel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHECKOUT;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_pilih;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
