/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author AULIA NUR RACHMATIKA
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksii;

public class tenda extends javax.swing.JFrame {
    

   

    int jumlah, harga, totalbayar;
    String NamaBarang;
private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("NO");
        model.addColumn("Nama Alat");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total Bayar");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

    }

    private void clear() {

        cb_pilih.setSelectedItem(null);
        txt_harga.setText(null);
        txt_jumlah.setText(null);
        txt_total.setText(null);

    }

    /**
     * Creates new form tenda
     */
    public tenda() {
        initComponents();
        tampilData();
        clear();
        sum();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_pilih = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        bt_save = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_tambah1 = new javax.swing.JButton();
        bayar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        bya = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NAMA ALAT");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 73, -1));

        jLabel2.setText("HARGA");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 62, -1));

        jLabel3.setText("JUMLAH");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setText("TOTAL");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        cb_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "DOME KAPASITAS 2-3 ORANG", "DOME KAPASITAS 3-4 ORANG", "DOME KAPASITAS 4-5 ORANG", "DOME KAPASITAS 6 ORANG", "DOME KAPASITAS 8 ORANG" }));
        cb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihActionPerformed(evt);
            }
        });
        jDesktopPane1.add(cb_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 67, 220, -1));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jDesktopPane1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 107, 107, -1));

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        jDesktopPane1.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 147, 107, -1));
        jDesktopPane1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 187, 107, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 70, 480, 90));

        jLabel5.setText("TENDA");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 11, 163, 25));

        bt_save.setText("SAVE");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 301, -1, -1));

        bt_hapus.setText("HAPUS");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 301, -1, -1));

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1391, -1, 0));

        bt_tambah.setText("TAMBAH ALAT");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 301, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 689, -1, -1));

        bt_tambah1.setText("CHEKOUT");
        bt_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambah1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(bt_tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 301, -1, -1));
        jDesktopPane1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 218, -1, -1));

        jTextField1.setText("TOTAL BAYAR");
        jDesktopPane1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 236, 92, 34));
        jDesktopPane1.add(bya, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 236, 90, 34));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/bg2.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -10, 970, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(498, 498, 498))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(852, 852, 852))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(txt_harga.getText());
        b = Integer.valueOf(txt_jumlah.getText());
        c = a * b;

        txt_total.setText(String.valueOf(c));

    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_hargaActionPerformed

    private void cb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihActionPerformed
        // TODO add your handling code here:
        NamaBarang = (String) cb_pilih.getSelectedItem();
        if (NamaBarang == "DOME KAPASITAS 2-3 ORANG") {
            harga = 25000;
        } else if (NamaBarang == "DOME KAPASITAS 3-4 ORANG") {
            harga = 28000;
        } else if (NamaBarang == "DOME KAPASITAS 4-5 ORANG") {
            harga = 30000;
        } else if (NamaBarang == "DOME KAPASITAS 6 ORANG") {
            harga = 32000;

        } else if (NamaBarang == "DOME KAPASITAS 8 ORANG") {
            harga = 35000;
        }
        txt_harga.setText(String.valueOf(harga));
    }//GEN-LAST:event_cb_pilihActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM barang WHERE Nama_Alat='" + cb_pilih.getSelectedItem() + "'";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Hapus data sukses");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tampilData();
        clear();
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        AlatRental ar = new AlatRental();
        ar.setVisible(true);
    }//GEN-LAST:event_bt_tambahActionPerformed
 public void sum() {
        int total = 0;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tbl.getValueAt(i, 4));
            total += amount;

        }
        bya.setText("" + total);

    }
    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("NAMA ALAT");
        model.addColumn("HARGA");
        model.addColumn("JUMLAH");
        model.addColumn("TOTAL");

        try {
            int no = 1;
            String sql = "SELECT *FROM barang";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.Statement stm = cn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            tbl.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }

        try {
            String sql = "INSERT INTO barang VALUES('" + cb_pilih.getSelectedItem() + "','" + txt_harga.getText() + "','" + txt_jumlah.getText() + "','" + txt_total.getText() + "')";
            java.sql.Connection cn = (Connection) koneksii.configDB();
            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Simpan data sukses");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        tampilData();
        clear();
        sum();

    }//GEN-LAST:event_bt_saveActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int baris = tbl.rowAtPoint(evt.getPoint());
        String nama = tbl.getValueAt(baris, 1).toString();
        cb_pilih.setSelectedItem(nama);

        String harga = tbl.getValueAt(baris, 2).toString();
        txt_harga.setText(harga);

        String jumlah = tbl.getValueAt(baris, 3).toString();
        txt_jumlah.setText(jumlah);

        String total = tbl.getValueAt(baris, 4).toString();
        txt_total.setText(total);

    }//GEN-LAST:event_tblMouseClicked

    private void bt_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambah1ActionPerformed
        // TODO add your handling code here:
        Input sw = new Input();
        sw.setVisible(true);
    }//GEN-LAST:event_bt_tambah1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bayar;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_save;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton bt_tambah1;
    private javax.swing.JTextField bya;
    private javax.swing.JComboBox<String> cb_pilih;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
